# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyGaadi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EasyGaadi
  pod 'Firebase/Messaging'
  # target 'EasyGaadi-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'EasyGaadiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EasyGaadi-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EasyGaadi-tvOS

  target 'EasyGaadi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
